import React from "react";
import "./Table.scss";
import TableComponent from "../../comp/table/TableComponent";

function Table() {
  const columns = [
    {
      title: "Employee Name",
      dataIndex: "name",
      sorter: true,
      width: "auto",
      fixed: "left",
    },
    {
      title: "Employee Id",
      dataIndex: "employee_id",
      sorter: true,
      width: "auto",
      fixed: "left",
    },
    {
      title: "Attendance Code",
      dataIndex: "attendance_code",
      sorter: true,
      width: "auto",
    },
    {
      title: "Gender",
      dataIndex: "gender",
      filters: [
        { text: "Male", value: "male" },
        { text: "Female", value: "female" },
      ],
      width: "auto",
    },

    {
      title: "Employee Status",
      dataIndex: "employee_status",
      sorter: true,
      width: "auto",
    },
    {
      title: "Designation",
      dataIndex: "designation",
      sorter: true,
      width: "auto",
    },
    {
      title: "Department",
      dataIndex: "department",
      sorter: true,
      width: "auto",
    },
    {
      title: "Date of joinning",
      dataIndex: "date_joining",
      sorter: true,
      width: "auto",
    },
    {
      title: "Date of Living",
      dataIndex: "date_living",
      sorter: true,
      width: "auto",
    },
    {
      title: "Contact ",
      dataIndex: "contact",
      sorter: true,
      width: "auto",
    },
    {
      title: "Email",
      dataIndex: "email",
      sorter: true,
      width: "auto",
    },
    {
      title: "Ifsc code ",
      dataIndex: "ifcs_code",
      sorter: true,
      width: "auto",
    },
    {
      title: "Date of Birth ",
      dataIndex: "date_of_birth",
      sorter: true,
      width: "auto",
    },
    {
      title: "Aadhar Number ",
      dataIndex: "aadhar",
      sorter: true,
      width: "auto",
    },
    {
      title: "Pan Number ",
      dataIndex: "pan",
      sorter: true,
      width: "auto",
    },
    {
      title: "Account Number ",
      dataIndex: "account_no",
      sorter: true,
      width: "auto",
    },
    {
      title: "Cost to Company ",
      dataIndex: "cost_company",
      sorter: true,
      width: "auto",
    },
    {
      title: "Employee Salary ",
      dataIndex: "e_salary",
      sorter: true,
      width: "auto",
    },
    {
      title: "Bank Name ",
      dataIndex: "bank_name",
      sorter: true,
      width: "auto",
    },
    {
      title: "Company Name ",
      dataIndex: "company_name",
      sorter: true,
      width: "auto",
    },
    {
      title: "Deduction ",
      dataIndex: "deduction",
      sorter: true,
      width: "auto",
    },
    {
      title: "Image ",
      dataIndex: "image",
      sorter: true,
      width: "auto",
    },
    {
      title: "Address ",
      dataIndex: "address",
      sorter: true,
      width: "auto",
    },
    {
      title: "Uan no ",
      dataIndex: "uan",
      sorter: true,
      width: "auto",
    },
    {
      title: "Employee id ",
      dataIndex: "emp_id",
      sorter: true,
      width: "auto",
    },
  ];

  const data = [
    {
      id: "1",
      name: "John Doe",
      gender: "male",
      employee_id: "002356",
      attendance_code: "568de9",
      employee_status: "On roll",
      designation: "developer",
      department: "abc",
      date_joining: "12/06/2023",
      date_living: "12/06/2025",
      contact: "9865894568",
      email: "info@gmail.com",
      ifcs_code: "KBR568P",
      date_of_birth: "15/8/2000",
      aadhar: "568945986345",
      pan: "ERT56I",
      account_no: "598655488065",
      cost_company: "56000",
      e_salary: "21000",
      bank_name: "sbi",
      company_name: "Pandoza Solutions",
      deduction: "786",
      image: "smile",
      address: "123- Pune, Maharastra",
      uan: "6556SDD5",
      emp_id: "12",
    },
    {
      id: "2",
      name: "John Doe",
      gender: "male",
      employee_id: "002356",
      attendance_code: "568de9",
      employee_status: "On roll",
      designation: "developer",
      department: "abc",
      date_joining: "12/06/2023",
      date_living: "12/06/2025",
      contact: "9865894568",
      email: "info@gmail.com",
      ifcs_code: "KBR568P",
      date_of_birth: "15/8/2000",
      aadhar: "568945986345",
      pan: "ERT56I",
      account_no: "598655488065",
      cost_company: "56000",
      e_salary: "21000",
      bank_name: "sbi",
      company_name: "Pandoza Solutions",
      deduction: "786",
      image: "smile",
      address: "123- Pune, Maharastra",
      uan: "6556SDD5",
      emp_id: "12",
    },
    {
      id: "3",
      name: "John Doe",
      gender: "male",
      employee_id: "002356",
      attendance_code: "568de9",
      employee_status: "On roll",
      designation: "developer",
      department: "abc",
      date_joining: "12/06/2023",
      date_living: "12/06/2025",
      contact: "9865894568",
      email: "info@gmail.com",
      ifcs_code: "KBR568P",
      date_of_birth: "15/8/2000",
      aadhar: "568945986345",
      pan: "ERT56I",
      account_no: "598655488065",
      cost_company: "56000",
      e_salary: "21000",
      bank_name: "sbi",
      company_name: "Pandoza Solutions",
      deduction: "786",
      image: "smile",
      address: "123- Pune, Maharastra",
      uan: "6556SDD5",
      emp_id: "12",
    },
    {
      id: "4",
      name: "John Doe",
      gender: "male",
      employee_id: "002356",
      attendance_code: "568de9",
      employee_status: "On roll",
      designation: "developer",
      department: "abc",
      date_joining: "12/06/2023",
      date_living: "12/06/2025",
      contact: "9865894568",
      email: "info@gmail.com",
      ifcs_code: "KBR568P",
      date_of_birth: "15/8/2000",
      aadhar: "568945986345",
      pan: "ERT56I",
      account_no: "598655488065",
      cost_company: "56000",
      e_salary: "21000",
      bank_name: "sbi",
      company_name: "Pandoza Solutions",
      deduction: "786",
      image: "smile",
      address: "123- Pune, Maharastra",
      uan: "6556SDD5",
      emp_id: "12",
    },
  ];

  return (
    <>
      <div className="table">
        <TableComponent data={data} columns={columns} />
      </div>
    </>
  );
}

export default Table;
